name: CI
on: [push, pull_request]

jobs:
  windows1: 
    name: test-windows1
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Script
        run: |
          cd packages/allow-scripts
          yarn run test-path-windows1
          npm run test-path-windows1
  windows2: 
    name: test-windows2
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Script
        run: |
          cd packages/allow-scripts
          yarn run test-path-windows2
          npm run test-path-windows2
  windows-tests: 
    name: test-windows-tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Tests
        run: |
          cd packages/allow-scripts
          yarn test
     